ObjCodeList = Main.o \
Args.o \
Rect.o \
Circle.o \
Object.o \
RunCommands.o \
String.o \
Tokens.o \
LinkedList.o \
CreateSvg.o \
CommandsObjs.o \
CommandsGeo.o \
CommandsEc.o \
CommandsPm.o \
CommandsTm.o \
CommandsQry.o \
CommandsVia.o \
CommandsDebug.o \
Geometry.o \
WriteTags.o \
Cidade.o \
ObjData.o \
ObjQuadTree.o \
ObjHashTable.o \
Quadra.o \
Point.o \
File.o \
Resumo.o \
ConvexHull.o \
Stack.o \
QuadTree.o \
QuadTreeDump.o \
QuadTreeSearch.o \
HashTable.o \
HashTableDump.o \
QuickSort.o \
Array.o \
Polygon.o \
Parser.o \
EstabComercial.o \
Pessoa.o \
Endereco.o \
Operadora.o \
Celular.o \
Graph.o \
GraphDump.o \
Rua.o

gccCommand = gcc -Wall -Wextra -pedantic -ansi -g

siguel : $(ObjCodeList)
	$(gccCommand) $(ObjCodeList) -lm -o siguel

Main.o : Main.c
	$(gccCommand) -c Main.c -o Main.o

Args.o : Args.c Args.h
	$(gccCommand) -c Args.c -o Args.o

Object.o : Object.c Object.h
	$(gccCommand) -c Object.c -o Object.o

Rect.o : Rect.c Rect.h
	$(gccCommand) -c Rect.c -o Rect.o

Circle.o : Circle.c Circle.h
	$(gccCommand) -c Circle.c -o Circle.o

Quadra.o : Quadra.h Quadra.c
	$(gccCommand) -c Quadra.c -o Quadra.o

Point.o : Point.h Point.c
	$(gccCommand) -c Point.c -o Point.o

Polygon.o : Polygon.h Polygon.c
	$(gccCommand) -c Polygon.c -o Polygon.o

RunCommands.o : RunCommands.c RunCommands.h
	$(gccCommand) -c RunCommands.c -o RunCommands.o

String.o : String.c String.h
	$(gccCommand) -c String.c -o String.o

Tokens.o : Tokens.c Tokens.h
	$(gccCommand) -c Tokens.c -o Tokens.o

LinkedList.o : LinkedList.c LinkedList.h
	$(gccCommand) -c LinkedList.c -o LinkedList.o

CreateSvg.o : CreateSvg.c CreateSvg.h
	$(gccCommand) -c CreateSvg.c -o CreateSvg.o

CommandsObjs.o : CommandsObjs.h CommandsObjs.c
	$(gccCommand) -c CommandsObjs.c -o CommandsObjs.o

CommandsGeo.o : CommandsGeo.h CommandsGeo.c
	$(gccCommand) -c CommandsGeo.c -o CommandsGeo.o

CommandsEc.o : CommandsEc.h CommandsEc.c
	$(gccCommand) -c CommandsEc.c -o CommandsEc.o

CommandsPm.o : CommandsPm.h CommandsPm.c
	$(gccCommand) -c CommandsPm.c -o CommandsPm.o

CommandsTm.o : CommandsTm.h CommandsTm.c
	$(gccCommand) -c CommandsTm.c -o CommandsTm.o

CommandsQry.o : CommandsQry.h CommandsQry.c
	$(gccCommand) -c CommandsQry.c -o CommandsQry.o

CommandsVia.o : CommandsVia.h CommandsVia.c
	$(gccCommand) -c CommandsVia.c -o CommandsVia.o

CommandsDebug.o : CommandsDebug.h CommandsDebug.c
	$(gccCommand) -c CommandsDebug.c -o CommandsDebug.o

Geometry.o : Geometry.h Geometry.c
	$(gccCommand) -c Geometry.c -o Geometry.o

WriteTags.o : WriteTags.h WriteTags.c
	$(gccCommand) -c WriteTags.c -o WriteTags.o

Cidade.o : Cidade.h Cidade.c
	$(gccCommand) -c Cidade.c -o Cidade.o

ObjData.o : ObjData.h ObjData.c
	$(gccCommand) -c ObjData.c -o ObjData.o

ObjQuadTree.o : ObjQuadTree.h ObjQuadTree.c
	$(gccCommand) -c ObjQuadTree.c -o ObjQuadTree.o

ObjHashTable.o : ObjHashTable.h ObjHashTable.c
	$(gccCommand) -c ObjHashTable.c -o ObjHashTable.o

File.o : File.c File.h
	$(gccCommand) -c File.c -o File.o

Resumo.o : Resumo.h Resumo.c
	$(gccCommand) -c Resumo.c -o Resumo.o

ConvexHull.o : ConvexHull.h ConvexHull.c
	$(gccCommand) -c ConvexHull.c -o ConvexHull.o

Stack.o : Stack.h Stack.c
	$(gccCommand) -c Stack.c -o Stack.o

QuadTree.o : QuadTree.h QuadTree.c
	$(gccCommand) -c QuadTree.c -o QuadTree.o

QuadTreeDump.o : QuadTreeDump.h QuadTreeDump.c
	$(gccCommand) -c QuadTreeDump.c -o QuadTreeDump.o

QuadTreeSearch.o : QuadTreeSearch.h QuadTreeSearch.c
	$(gccCommand) -c QuadTreeSearch.c -o QuadTreeSearch.o

HashTable.o : HashTable.h HashTable.c
	$(gccCommand) -c HashTable.c -o HashTable.o

HashTableDump.o : HashTableDump.h HashTableDump.c
	$(gccCommand) -c HashTableDump.c -o HashTableDump.o

QuickSort.o : QuickSort.h QuickSort.c
	$(gccCommand) -c QuickSort.c -o QuickSort.o

Array.o : Array.h Array.c
	$(gccCommand) -c Array.c -o Array.o

Parser.o : Parser.h Parser.c
	$(gccCommand) -c Parser.c -o Parser.o

EstabComercial.o : EstabComercial.h EstabComercial.c
	$(gccCommand) -c EstabComercial.c -o EstabComercial.o

Pessoa.o : Pessoa.h Pessoa.c
	$(gccCommand) -c Pessoa.c -o Pessoa.o

Endereco.o : Endereco.h Endereco.c
	$(gccCommand) -c Endereco.c -o Endereco.o

Operadora.o : Operadora.h Operadora.c
	$(gccCommand) -c Operadora.c -o Operadora.o

Celular.o : Celular.h Celular.c
	$(gccCommand) -c Celular.c -o Celular.o

Graph.o : Graph.h Graph.c
	$(gccCommand) -c Graph.c -o Graph.o

GraphDump.o : GraphDump.h GraphDump.c
	$(gccCommand) -c GraphDump.c -o GraphDump.o

Rua.o : Rua.h Rua.c
	$(gccCommand) -c Rua.c -o Rua.o

clean :
	rm *.o

check :
	$(gccCommand) -fsyntax-only *.c *.h
